'use client';

import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { Button } from '@/components/ui/button';
import { motion, useMotionValue, useTransform, useSpring, AnimatePresence } from 'framer-motion';
import {
  Brain,
  Target,
  TrendingUp,
  Users,
  BookOpen,
  Award,
  ChevronDown,
  Star,
  ArrowRight,
  Zap,
  Shield,
  Globe,
  Sparkles,
  Check,
  X,
  BarChart3,
  Clock,
  Rocket,
  MessageSquare,
  ArrowUpRight,
  Layers,
  Lightbulb,
  GitBranch,
  Cpu,
  LineChart,
  Workflow,
  Terminal,
  FileCode,
  Palette,
} from 'lucide-react';
import { useState, useEffect, useRef, useCallback, ReactNode, useMemo } from 'react';

/* ================================================================
   DATA
   ================================================================ */

const bootSequence = [
  { text: 'Initializing AI engine...', icon: Cpu },
  { text: 'Analyzing skill patterns...', icon: Brain },
  { text: 'Generating learning roadmap...', icon: GitBranch },
  { text: 'Optimizing recommendations...', icon: Sparkles },
];

const features = [
  { icon: Brain, title: 'AI-Powered Paths', description: 'Personalized learning routes generated by analyzing your skills, goals, and market demand.', color: 'from-violet-500 to-purple-600' },
  { icon: Target, title: 'Career Roadmaps', description: 'Visual step-by-step paths showing exactly what to learn for your dream role.', color: 'from-blue-500 to-cyan-500' },
  { icon: LineChart, title: 'Progress Analytics', description: 'Real-time dashboards tracking your growth with actionable insights.', color: 'from-emerald-500 to-green-500' },
  { icon: Users, title: 'Community', description: 'Connect with 50K+ learners, share milestones, and grow together.', color: 'from-orange-500 to-amber-500' },
  { icon: Layers, title: 'Curated Resources', description: 'Hand-picked courses, tutorials, and projects for every learning path.', color: 'from-pink-500 to-rose-500' },
  { icon: Award, title: 'Certifications', description: 'Earn verified certificates to showcase your skills to employers.', color: 'from-teal-500 to-cyan-500' },
];

const bentoItems = [
  { icon: Brain, title: 'AI Engine', desc: 'GPT-powered skill analysis', span: 'col-span-1 row-span-1', gradient: 'from-violet-500/10 to-purple-600/10' },
  { icon: GitBranch, title: 'Roadmaps', desc: 'Dynamic career paths', span: 'col-span-1 row-span-1', gradient: 'from-blue-500/10 to-cyan-500/10' },
  { icon: BarChart3, title: 'Analytics', desc: 'Real-time dashboards', span: 'col-span-1 row-span-1', gradient: 'from-emerald-500/10 to-green-500/10' },
  { icon: Terminal, title: 'Projects', desc: 'Build real-world apps', span: 'col-span-1 row-span-1', gradient: 'from-orange-500/10 to-amber-500/10' },
  { icon: FileCode, title: 'Challenges', desc: 'Skill-building exercises', span: 'col-span-1 row-span-1', gradient: 'from-pink-500/10 to-rose-500/10' },
  { icon: Palette, title: 'Portfolio', desc: 'Showcase your work', span: 'col-span-1 row-span-1', gradient: 'from-teal-500/10 to-cyan-500/10' },
];

const beforeAfter = [
  { without: 'Random YouTube tutorials', with: 'Structured AI-curated path' },
  { without: 'No clear career direction', with: 'Step-by-step roadmap' },
  { without: 'Guessing what to learn next', with: 'Data-driven recommendations' },
  { without: 'No progress tracking', with: 'Real-time analytics dashboard' },
  { without: 'Isolated learning', with: 'Community + mentorship' },
  { without: 'No proof of skills', with: 'Verified certificates' },
];

const stats = [
  { value: 50000, suffix: '+', label: 'Active Learners', icon: Users },
  { value: 200, suffix: '+', label: 'Learning Paths', icon: BookOpen },
  { value: 95, suffix: '%', label: 'Success Rate', icon: TrendingUp },
  { value: 4.9, suffix: '', label: 'Average Rating', icon: Star },
];

const testimonials = [
  { name: 'Sarah Johnson', role: 'Frontend Developer at Google', initials: 'SJ', content: 'SkillBridge AI helped me go from junior to senior in 8 months. The personalized roadmap was exactly what I needed.', rating: 5 },
  { name: 'Michael Chen', role: 'Data Scientist at Meta', initials: 'MC', content: 'The AI recommendations were spot-on. I learned exactly what I needed for my dream job. Highly recommend!', rating: 5 },
  { name: 'Emily Rodriguez', role: 'ML Engineer at Amazon', initials: 'ER', content: 'The career roadmap feature is incredible. I could visualize exactly what skills I needed for my target role.', rating: 5 },
];

const faqs = [
  { question: 'What is SkillBridge AI?', answer: 'SkillBridge AI is an AI-powered learning platform that creates personalized learning paths and career roadmaps to help you achieve your professional goals faster.' },
  { question: 'How does the AI recommendation work?', answer: 'Our AI analyzes your current skills, career goals, and learning preferences to generate a customized learning path tailored specifically for you.' },
  { question: 'Is SkillBridge AI free to use?', answer: 'We offer a generous free tier with core features. Premium plans unlock AI coaching, priority support, and advanced analytics.' },
  { question: 'Can I switch career paths?', answer: 'Absolutely. Update your goals anytime and the AI will regenerate your roadmap to match your new direction.' },
];

/* ================================================================
   HOOKS
   ================================================================ */

function useCountUp(end: number, duration: number = 2000, decimals: number = 0) {
  const [count, setCount] = useState(0);
  const [hasStarted, setHasStarted] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting && !hasStarted) setHasStarted(true); },
      { threshold: 0.3 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [hasStarted]);

  useEffect(() => {
    if (!hasStarted) return;
    let startTime: number;
    const animate = (timestamp: number) => {
      if (!startTime) startTime = timestamp;
      const progress = Math.min((timestamp - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setCount(Number((eased * end).toFixed(decimals)));
      if (progress < 1) requestAnimationFrame(animate);
    };
    requestAnimationFrame(animate);
  }, [hasStarted, end, duration, decimals]);

  return { count, ref };
}

function useMouseParallax(ref: React.RefObject<HTMLDivElement | null>, strength: number = 20) {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const springX = useSpring(x, { stiffness: 150, damping: 20 });
  const springY = useSpring(y, { stiffness: 150, damping: 20 });

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const handleMove = (e: MouseEvent) => {
      const rect = el.getBoundingClientRect();
      const centerX = rect.left + rect.width / 2;
      const centerY = rect.top + rect.height / 2;
      x.set((e.clientX - centerX) / rect.width * strength);
      y.set((e.clientY - centerY) / rect.height * strength);
    };
    window.addEventListener('mousemove', handleMove, { passive: true });
    return () => window.removeEventListener('mousemove', handleMove);
  }, [ref, strength, x, y]);

  return { springX, springY };
}

/* ================================================================
   SUB-COMPONENTS
   ================================================================ */

function BootSequence({ onComplete }: { onComplete: () => void }) {
  const [currentLine, setCurrentLine] = useState(0);
  const [progress, setProgress] = useState(0);
  const [isDone, setIsDone] = useState(false);

  useEffect(() => {
    if (currentLine < bootSequence.length) {
      const timer = setTimeout(() => setCurrentLine((p) => p + 1), 600);
      return () => clearTimeout(timer);
    } else {
      const timer = setTimeout(() => {
        setIsDone(true);
        setTimeout(onComplete, 400);
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [currentLine, onComplete]);

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress((p) => Math.min(100, p + Math.random() * 8 + 2));
    }, 50);
    return () => clearInterval(interval);
  }, []);

  return (
    <motion.div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-background"
      animate={isDone ? { opacity: 0 } : { opacity: 1 }}
      transition={{ duration: 0.4 }}
    >
      <div className="w-full max-w-md px-6">
        <div className="mb-8 text-center">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary to-accent flex items-center justify-center mx-auto mb-4 shadow-lg shadow-primary/20">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-2xl font-bold gradient-text">SkillBridge AI</h1>
        </div>

        <div className="space-y-3 mb-8">
          {bootSequence.map((line, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -10 }}
              animate={i < currentLine ? { opacity: 1, x: 0 } : i === currentLine ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.3 }}
              className={`flex items-center gap-3 text-sm ${i < currentLine ? 'text-foreground' : i === currentLine ? 'text-primary' : 'text-muted-foreground/40'}`}
            >
              {i < currentLine ? (
                <Check className="w-4 h-4 text-success shrink-0" />
              ) : i === currentLine ? (
                <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}>
                  <line.icon className="w-4 h-4 text-primary shrink-0" />
                </motion.div>
              ) : (
                <line.icon className="w-4 h-4 shrink-0" />
              )}
              <span className="font-mono">{line.text}</span>
            </motion.div>
          ))}
        </div>

        <div className="space-y-2">
          <div className="h-1.5 bg-muted/50 rounded-full overflow-hidden">
            <motion.div
              className="h-full bg-gradient-to-r from-primary to-accent rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.1 }}
            />
          </div>
          <p className="text-xs text-muted-foreground text-center font-mono">{Math.round(progress)}% complete</p>
        </div>
      </div>
    </motion.div>
  );
}

function FloatingCard({ children, className, delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay, ease: [0.16, 1, 0.3, 1] }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

function RoadmapNode({ label, delay, active = false }: { label: string; delay: number; active?: boolean }) {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.8 }}
      whileInView={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.4, delay, ease: [0.34, 1.56, 0.64, 1] }}
      viewport={{ once: true }}
      className={`flex items-center gap-3 px-4 py-3 rounded-xl border transition-all duration-300 ${
        active
          ? 'bg-primary/10 border-primary/30 text-primary shadow-sm shadow-primary/10'
          : 'bg-card/50 border-border/50 text-foreground hover:border-primary/20'
      }`}
    >
      <div className={`w-2 h-2 rounded-full ${active ? 'bg-primary animate-pulse' : 'bg-muted-foreground/30'}`} />
      <span className="text-sm font-medium">{label}</span>
    </motion.div>
  );
}

function StatCard({ value, suffix, label, icon: Icon, index }: { value: number; suffix: string; label: string; icon: React.ElementType; index: number }) {
  const { count, ref } = useCountUp(value, 2000, value % 1 !== 0 ? 1 : 0);
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      viewport={{ once: true }}
      className="text-center p-6 rounded-2xl bg-card/50 border border-border/50 hover:border-primary/20 hover:bg-card transition-all duration-300"
    >
      <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
        <Icon className="w-6 h-6 text-primary" />
      </div>
      <div className="text-4xl md:text-5xl font-bold gradient-text mb-2 font-display tracking-tighter">
        {value >= 1000 ? `${(count / 1000).toFixed(count >= 1000 ? 0 : 1)}K` : count}{suffix}
      </div>
      <div className="text-sm text-muted-foreground font-medium">{label}</div>
    </motion.div>
  );
}

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border border-border/50 rounded-2xl overflow-hidden bg-card/50 hover:border-border transition-colors duration-200">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between w-full px-6 py-5 text-left hover:bg-muted/30 transition-colors duration-200"
        aria-expanded={isOpen}
      >
        <span className="font-semibold text-foreground pr-4">{question}</span>
        <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform duration-300 shrink-0 ${isOpen ? 'rotate-180' : ''}`} />
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: 'easeInOut' }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-5 text-muted-foreground leading-relaxed">{answer}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* ================================================================
   PAGE
   ================================================================ */

export default function HomePage() {
  const [booted, setBooted] = useState(false);
  const [bootDone, setBootDone] = useState(false);
  const heroRef = useRef<HTMLDivElement>(null);
  const { springX, springY } = useMouseParallax(heroRef, 15);
  const [assistantOpen, setAssistantOpen] = useState(false);

  useEffect(() => {
    if (booted) return;
    const timer = setTimeout(() => {
      setBooted(true);
      setTimeout(() => setBootDone(true), 500);
    }, 2800);
    return () => clearTimeout(timer);
  }, [booted]);

  const roadmapGoal = useState('Frontend Developer');
  const roadmapLevel = useState('Intermediate');
  const roadmapTime = useState('10 hrs/week');

  return (
    <div className="overflow-hidden">
      {/* Boot Sequence */}
      {!bootDone && <BootSequence onComplete={() => setBooted(true)} />}

      {/* ============================== HERO ============================== */}
      <section ref={heroRef} className="relative min-h-[90vh] flex items-center overflow-hidden">
        {/* Background */}
        <div className="absolute inset-0 bg-gradient-to-br from-background via-background to-primary/5" />
        <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(ellipse at 20% 50%, var(--primary) 0%, transparent 50%)', opacity: 0.06 }} />
        <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(ellipse at 80% 20%, var(--accent) 0%, transparent 50%)', opacity: 0.04 }} />
        <div className="absolute top-1/3 left-1/4 w-[500px] h-[500px] bg-primary/8 rounded-full blur-[120px]" />
        <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-accent/8 rounded-full blur-[100px]" />
        <div className="absolute inset-0 grid-pattern opacity-[0.15]" />
        <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent" />

        <Container className="relative z-10">
          <div className="flex flex-col lg:flex-row items-center gap-12 lg:gap-20 py-12 md:py-20">
            {/* Left: Text */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={bootDone ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
              className="flex-1 text-center lg:text-left"
            >
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={bootDone ? { opacity: 1, scale: 1 } : {}}
                transition={{ duration: 0.5, delay: 0.2 }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-8"
              >
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-sm font-medium text-primary">AI-Powered Learning Platform</span>
              </motion.div>

              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold mb-6 leading-[1.08] tracking-tight">
                <span className="text-foreground">Your AI-Powered</span>
                <span className="block gradient-text mt-1">Career Companion</span>
              </h1>

              <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-xl mx-auto lg:mx-0 leading-relaxed">
                Get personalized learning paths, career roadmaps, and AI-driven recommendations to accelerate your professional growth.
              </p>

              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Link href="/register">
                  <Button size="lg" className="w-full sm:w-auto text-base px-8">
                    Create Free Account
                    <ArrowRight className="w-5 h-5" />
                  </Button>
                </Link>
                <Link href="/learning-paths">
                  <Button size="lg" variant="outline" className="w-full sm:w-auto text-base px-8">
                    Explore Paths
                  </Button>
                </Link>
              </div>

              <div className="flex items-center gap-6 mt-10 justify-center lg:justify-start">
                <div className="flex -space-x-3">
                  {['SJ', 'MC', 'ER', 'JK', 'AL'].map((initials, i) => (
                    <div key={i} className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center text-white text-sm font-medium border-2 border-background">
                      {initials}
                    </div>
                  ))}
                </div>
                <div className="text-left">
                  <div className="flex items-center gap-1">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-warning text-warning" />
                    ))}
                  </div>
                  <p className="text-sm text-muted-foreground">50,000+ happy learners</p>
                </div>
              </div>
            </motion.div>

            {/* Right: Interactive Dashboard Preview */}
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              animate={bootDone ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.7, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
              className="flex-1 w-full max-w-lg"
            >
              <motion.div style={{ x: springX, y: springY }} className="relative">
                <div className="absolute -inset-4 bg-gradient-to-r from-primary/20 to-accent/20 rounded-3xl blur-2xl" />
                <div className="relative glass-strong rounded-3xl shadow-2xl border border-border/50 p-8">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-lg shadow-primary/20">
                      <Brain className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-foreground">AI Learning Path</h3>
                      <p className="text-sm text-muted-foreground">Personalized for you</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    {['React Fundamentals', 'Advanced TypeScript', 'System Design'].map((item, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -20 }}
                        animate={bootDone ? { opacity: 1, x: 0 } : {}}
                        transition={{ duration: 0.5, delay: 0.5 + i * 0.1 }}
                        className="flex items-center gap-3 p-4 bg-muted/30 rounded-xl border border-border/30"
                      >
                        <div className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium ${i === 0 ? 'bg-success/20 text-success' : 'bg-muted/50 text-muted-foreground'}`}>
                          {i === 0 ? '\u2713' : i + 1}
                        </div>
                        <span className={`text-sm font-medium ${i === 0 ? 'text-success' : 'text-foreground'}`}>{item}</span>
                      </motion.div>
                    ))}
                  </div>

                  <div className="mt-6 pt-6 border-t border-border/50">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Progress</span>
                      <span className="font-semibold text-primary">33%</span>
                    </div>
                    <div className="mt-3 h-2 bg-muted/50 rounded-full overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={bootDone ? { width: '33%' } : {}}
                        transition={{ duration: 1, delay: 0.8 }}
                        className="h-full bg-gradient-to-r from-primary to-accent rounded-full"
                      />
                    </div>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* ============================== AI ROADMAP GENERATOR ============================== */}
      <section className="py-20 md:py-28">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">Roadmap Generator</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Your Path in 30 Seconds</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">Tell us your goal and watch AI generate your personalized career roadmap.</p>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-10 items-center">
            {/* Input Form */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              viewport={{ once: true }}
              className="glass-strong rounded-3xl p-8 border border-border/50"
            >
              <div className="space-y-5">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Your Goal</label>
                  <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-muted/30 border border-border/50">
                    <Target className="w-5 h-5 text-primary shrink-0" />
                    <span className="text-sm font-medium">{roadmapGoal[0]}</span>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Skill Level</label>
                  <div className="flex gap-2">
                    {['Beginner', 'Intermediate', 'Advanced'].map((level) => (
                      <div
                        key={level}
                        className={`flex-1 text-center py-2.5 rounded-xl text-sm font-medium border transition-all ${
                          roadmapLevel[0] === level
                            ? 'bg-primary/10 border-primary/30 text-primary'
                            : 'bg-muted/30 border-border/50 text-muted-foreground'
                        }`}
                      >
                        {level}
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Study Time</label>
                  <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-muted/30 border border-border/50">
                    <Clock className="w-5 h-5 text-primary shrink-0" />
                    <span className="text-sm font-medium">{roadmapTime[0]}</span>
                  </div>
                </div>
                <Link href="/register">
                  <Button className="w-full" size="lg">
                    <Sparkles className="w-5 h-5" />
                    Generate My Roadmap
                  </Button>
                </Link>
              </div>
            </motion.div>

            {/* Roadmap Preview */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              viewport={{ once: true }}
              className="space-y-3"
            >
              <div className="glass-strong rounded-3xl p-6 border border-border/50">
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                    <Rocket className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground">Frontend Developer</h4>
                    <p className="text-xs text-muted-foreground">Intermediate · 10 hrs/week</p>
                  </div>
                </div>
                <div className="space-y-2">
                  <RoadmapNode label="HTML & CSS Mastery" delay={0.1} active />
                  <RoadmapNode label="JavaScript Fundamentals" delay={0.2} />
                  <RoadmapNode label="React & Next.js" delay={0.3} />
                  <RoadmapNode label="TypeScript Deep Dive" delay={0.4} />
                  <RoadmapNode label="Testing & CI/CD" delay={0.5} />
                  <RoadmapNode label="System Design Basics" delay={0.6} />
                </div>
              </div>
              <Link href="/register" className="block">
                <Button variant="outline" className="w-full">
                  Create Free Account
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </Link>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* ============================== STORYTELLING: PROBLEM → SOLUTION ============================== */}
      <section className="py-20 md:py-28 bg-card/30">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">The Problem</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Learning Without Direction</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">
              Most developers waste months jumping between tutorials. No roadmap. No plan. No progress.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {/* Without */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              viewport={{ once: true }}
              className="rounded-2xl border border-destructive/20 bg-destructive/5 p-6"
            >
              <div className="flex items-center gap-3 mb-5">
                <div className="w-10 h-10 rounded-xl bg-destructive/10 flex items-center justify-center">
                  <X className="w-5 h-5 text-destructive" />
                </div>
                <h3 className="font-semibold text-foreground">Without SkillBridge</h3>
              </div>
              <div className="space-y-3">
                {beforeAfter.map((item, i) => (
                  <div key={i} className="flex items-center gap-3 text-sm">
                    <X className="w-4 h-4 text-destructive shrink-0" />
                    <span className="text-muted-foreground">{item.without}</span>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* With */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              viewport={{ once: true }}
              className="rounded-2xl border border-success/20 bg-success/5 p-6"
            >
              <div className="flex items-center gap-3 mb-5">
                <div className="w-10 h-10 rounded-xl bg-success/10 flex items-center justify-center">
                  <Check className="w-5 h-5 text-success" />
                </div>
                <h3 className="font-semibold text-foreground">With SkillBridge</h3>
              </div>
              <div className="space-y-3">
                {beforeAfter.map((item, i) => (
                  <div key={i} className="flex items-center gap-3 text-sm">
                    <Check className="w-4 h-4 text-success shrink-0" />
                    <span className="text-foreground font-medium">{item.with}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* ============================== BENTO GRID ============================== */}
      <section className="py-20 md:py-28">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">Features</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Everything You Need</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">Powerful tools to learn smarter, track progress, and advance your career.</p>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {bentoItems.map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                viewport={{ once: true }}
                className={`group p-6 rounded-2xl bg-gradient-to-br ${item.gradient} border border-border/50 hover:border-primary/30 hover:shadow-xl hover:shadow-primary/5 transition-all duration-300 ${item.span}`}
              >
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/10 to-accent/10 flex items-center justify-center mb-4 group-hover:from-primary/20 group-hover:to-accent/20 transition-all duration-300">
                  <item.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-semibold text-foreground mb-1">{item.title}</h3>
                <p className="text-sm text-muted-foreground">{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* ============================== ANIMATED STATISTICS ============================== */}
      <section className="py-20 md:py-28 bg-card/30">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">Impact</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Trusted by Thousands</h2>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((stat, i) => (
              <StatCard key={i} {...stat} index={i} />
            ))}
          </div>
        </Container>
      </section>

      {/* ============================== DASHBOARD PREVIEW ============================== */}
      <section className="py-20 md:py-28">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">Dashboard</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Your Learning Command Center</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">Track progress, discover insights, and stay on top of your learning goals.</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            viewport={{ once: true }}
            className="relative max-w-5xl mx-auto"
          >
            <div className="absolute -inset-8 bg-gradient-to-r from-primary/10 to-accent/10 rounded-3xl blur-3xl" />
            <div className="relative glass-strong rounded-3xl border border-border/50 p-6 md:p-8 shadow-premium-xl">
              {/* Mockup Header */}
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground">Dashboard</p>
                    <p className="text-xs text-muted-foreground">Welcome back, Sarah</p>
                  </div>
                </div>
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-success" />
                  <div className="w-3 h-3 rounded-full bg-warning" />
                  <div className="w-3 h-3 rounded-full bg-muted-foreground/30" />
                </div>
              </div>

              {/* Mockup Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                {[
                  { label: 'Paths Enrolled', value: '12', icon: BookOpen, color: 'text-primary' },
                  { label: 'Completed', value: '8', icon: Award, color: 'text-success' },
                  { label: 'Hours Learned', value: '156', icon: Clock, color: 'text-info' },
                  { label: 'Streak', value: '23 days', icon: Zap, color: 'text-warning' },
                ].map((s, i) => (
                  <div key={i} className="p-4 rounded-xl bg-muted/30 border border-border/30">
                    <s.icon className={`w-5 h-5 ${s.color} mb-2`} />
                    <p className="text-xl font-bold text-foreground">{s.value}</p>
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                  </div>
                ))}
              </div>

              {/* Mockup Chart */}
              <div className="rounded-xl bg-muted/20 border border-border/30 p-4">
                <div className="flex items-center justify-between mb-4">
                  <p className="text-sm font-medium text-foreground">Learning Activity</p>
                  <div className="flex gap-3 text-xs text-muted-foreground">
                    <span>Week</span>
                    <span>Month</span>
                    <span className="text-primary font-medium">Year</span>
                  </div>
                </div>
                <div className="flex items-end gap-2 h-32">
                  {[40, 65, 45, 80, 55, 90, 70, 85, 60, 95, 75, 88].map((h, i) => (
                    <motion.div
                      key={i}
                      initial={{ height: 0 }}
                      whileInView={{ height: `${h}%` }}
                      transition={{ duration: 0.5, delay: i * 0.05 }}
                      viewport={{ once: true }}
                      className="flex-1 bg-gradient-to-t from-primary/60 to-primary/20 rounded-t-md"
                    />
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </Container>
      </section>

      {/* ============================== TESTIMONIALS ============================== */}
      <section className="py-20 md:py-28 bg-card/30">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">Testimonials</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Success Stories</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">See how SkillBridge AI has helped professionals transform their careers.</p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {testimonials.map((t, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                viewport={{ once: true }}
                className="p-6 rounded-2xl bg-card/50 border border-border/50 hover:bg-card hover:shadow-xl transition-all duration-300"
              >
                <div className="flex gap-1 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} className="w-5 h-5 fill-warning text-warning" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-6 leading-relaxed">&ldquo;{t.content}&rdquo;</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                    <span className="text-sm font-semibold text-white">{t.initials}</span>
                  </div>
                  <div>
                    <div className="font-semibold text-sm text-foreground">{t.name}</div>
                    <div className="text-xs text-muted-foreground">{t.role}</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* ============================== FAQ ============================== */}
      <section className="py-20 md:py-28">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="font-overline text-primary mb-3 block">FAQ</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-heading tracking-tight mb-4">Got Questions?</h2>
            <p className="text-lg text-muted-foreground font-body max-w-2xl mx-auto">We have answers.</p>
          </motion.div>
          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, i) => (
              <FAQItem key={i} {...faq} />
            ))}
          </div>
        </Container>
      </section>

      {/* ============================== CTA ============================== */}
      <section className="py-20 md:py-28">
        <Container>
          <div className="relative rounded-3xl bg-gradient-to-r from-primary to-accent p-12 md:p-16 text-center overflow-hidden">
            <div className="absolute inset-0 opacity-10 grid-pattern" />
            <div className="absolute inset-0 bg-gradient-to-r from-primary/20 to-accent/20" />
            <div className="relative z-10">
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 tracking-tight">
                Ready to Accelerate Your Career?
              </h2>
              <p className="text-lg text-white/90 mb-8 max-w-2xl mx-auto leading-relaxed">
                Join 50,000+ learners transforming their careers with AI-powered learning paths.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/register">
                  <Button size="lg" className="bg-white/95 text-primary hover:bg-white shadow-lg hover:shadow-xl text-base px-8">
                    Get Started Free
                    <ArrowRight className="w-5 h-5" />
                  </Button>
                </Link>
                <Link href="/learning-paths">
                  <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10 text-base px-8">
                    Explore Paths
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ============================== AI ASSISTANT WIDGET ============================== */}
      <div className="fixed bottom-6 right-6 z-50">
        <AnimatePresence>
          {assistantOpen && (
            <motion.div
              initial={{ opacity: 0, y: 20, scale: 0.9 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 20, scale: 0.9 }}
              transition={{ duration: 0.2 }}
              className="mb-4 w-80 glass-strong rounded-2xl border border-border/50 shadow-premium-xl overflow-hidden"
            >
              <div className="p-4 border-b border-border/50">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                    <MessageSquare className="w-4 h-4 text-white" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground">AI Assistant</p>
                    <p className="text-xs text-success flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-success" />
                      Online
                    </p>
                  </div>
                </div>
              </div>
              <div className="p-4 space-y-3">
                <div className="p-3 rounded-xl bg-muted/30 border border-border/30 text-sm text-muted-foreground">
                  Hi! I can help you choose the right learning path. What is your career goal?
                </div>
                <div className="flex gap-2">
                  <button className="flex-1 px-3 py-2 rounded-lg bg-primary/10 border border-primary/20 text-primary text-xs font-medium hover:bg-primary/20 transition-colors">
                    Frontend Dev
                  </button>
                  <button className="flex-1 px-3 py-2 rounded-lg bg-muted/30 border border-border/30 text-foreground text-xs font-medium hover:bg-muted/50 transition-colors">
                    Data Science
                  </button>
                  <button className="flex-1 px-3 py-2 rounded-lg bg-muted/30 border border-border/30 text-foreground text-xs font-medium hover:bg-muted/50 transition-colors">
                    ML Engineer
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <button
          onClick={() => setAssistantOpen(!assistantOpen)}
          className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-accent text-white shadow-lg shadow-primary/25 hover:shadow-xl hover:shadow-primary/30 flex items-center justify-center transition-all duration-200 hover:scale-105 active:scale-95"
          aria-label="Toggle AI Assistant"
        >
          {assistantOpen ? (
            <X className="w-6 h-6" />
          ) : (
            <MessageSquare className="w-6 h-6" />
          )}
        </button>
      </div>
    </div>
  );
}
