import { Metadata } from 'next';
import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { Section } from '@/components/ui/Section';
import { ChevronRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service - SkillBridge AI',
  description: 'Review the terms and conditions governing your use of SkillBridge AI platform and services.',
};

const sections = [
  {
    title: 'Acceptance of Terms',
    content: `By accessing or using SkillBridge AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform. We reserve the right to modify these terms at any time, and your continued use constitutes acceptance of any changes.`,
  },
  {
    title: 'Eligibility',
    content: `You must be at least 16 years old to use SkillBridge AI. By creating an account, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these terms. If you are using the platform on behalf of an organization, you represent that you have authority to bind that organization.`,
  },
  {
    title: 'Account Responsibilities',
    content: `**Account Security:** You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately if you suspect unauthorized access to your account.

**Accuracy:** You agree to provide accurate, current, and complete information during registration and to keep your account information up to date.

**Single Account:** Each user may maintain only one account. Creating multiple accounts to circumvent platform rules is prohibited.

**Account Transfer:** Your account is personal to you and may not be transferred, sold, or shared with others without our written consent.`,
  },
  {
    title: 'Platform Usage',
    content: `**Permitted Use:** SkillBridge AI is designed for personal and professional learning. You may use the platform to access learning paths, complete courses, generate AI-powered content, and track your progress.

**Prohibited Conduct:** You agree not to:
- Use the platform for any unlawful purpose
- Attempt to gain unauthorized access to any part of the platform
- Interfere with or disrupt the platform or servers
- Reverse engineer, decompile, or disassemble any part of the platform
- Use automated tools to access or scrape content
- Impersonate another person or misrepresent your identity
- Upload malicious code or harmful content
- Resell or redistribute platform content without authorization`,
  },
  {
    title: 'Intellectual Property',
    content: `**Our Content:** All content on SkillBridge AI, including courses, learning materials, AI-generated content, software, and design, is owned by us or our licensors and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works without our express permission.

**Your Content:** You retain ownership of content you create and upload to the platform. By submitting content, you grant us a non-exclusive license to use, display, and distribute your content as necessary to operate the platform.

**AI-Generated Content:** Content generated by our AI tools based on your inputs is licensed to you for personal and professional use. You may use AI-generated resumes, roadmaps, and recommendations in your career pursuits. We retain the right to use anonymized, aggregated data to improve our AI models.`,
  },
  {
    title: 'Learning Path Enrollment',
    content: `**Enrollment:** When you enroll in a learning path, you receive a license to access the course materials for the duration of your subscription or as otherwise specified.

**Completion:** Completing a learning path requires finishing all required modules and assessments. Certificates are awarded upon verified completion and remain valid indefinitely.

**No Guarantees:** While we strive to provide high-quality education, we do not guarantee specific career outcomes, job placements, or salary improvements as a result of completing learning paths.`,
  },
  {
    title: 'Payment Terms',
    content: `**Pricing:** Subscription fees and pricing are displayed on our pricing page and are subject to change with 30 days notice. Promotional pricing applies only to the initial subscription period.

**Billing:** Subscriptions are billed in advance on a monthly or annual basis. Payment is processed through our third-party payment processor (Stripe). You agree to the payment terms established by Stripe.

**Refunds:** Monthly subscriptions are non-refundable. Annual subscriptions may be refunded within 30 days of purchase. After 30 days, the remaining balance of your subscription is non-refundable.

**Cancellation:** You may cancel your subscription at any time. Your access continues until the end of the current billing period. Cancellation does not entitle you to a prorated refund for unused portions of a billing period.`,
  },
  {
    title: 'Third-Party Services',
    content: `Our platform integrates with third-party services including Google, GitHub, and Facebook for authentication. Your use of these services is governed by their respective terms of privacy policies. We are not responsible for the practices of third-party services and encourage you to review their terms.`,
  },
  {
    title: 'Disclaimers',
    content: `**As-Is Basis:** SkillBridge AI is provided on an "as-is" and "as-available" basis without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.

**No Warranty:** We do not warrant that the platform will be uninterrupted, error-free, or free of viruses or harmful components. We do not guarantee the accuracy, completeness, or reliability of any content on the platform.

**Limitation of Liability:** To the maximum extent permitted by law, SkillBridge AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: 'Indemnification',
    content: `You agree to indemnify and hold harmless SkillBridge AI, its officers, directors, employees, and agents from any claims, losses, damages, liabilities, costs, and expenses (including reasonable attorneys fees) arising from your use of the platform, violation of these terms, or infringement of any third-party rights.`,
  },
  {
    title: 'Termination',
    content: `We may suspend or terminate your account at any time for conduct that violates these terms, is harmful to other users, or is otherwise objectionable. Upon termination:
- Your right to access the platform ceases immediately
- We may retain certain data as required by law or for legitimate business purposes
- Provisions of these terms that by their nature should survive termination will remain in effect`,
  },
  {
    title: 'Governing Law',
    content: `These Terms of Service are governed by the laws of the State of California, United States, without regard to its conflict of law provisions. Any disputes arising from these terms or your use of the platform shall be resolved in the state or federal courts located in San Francisco County, California.`,
  },
  {
    title: 'Dispute Resolution',
    content: `Any dispute arising from these terms shall first be attempted to be resolved through informal negotiation. If informal resolution fails, disputes shall be resolved through binding arbitration administered by the American Arbitration Association. The arbitration shall take place in San Francisco, California, and the language of arbitration shall be English.`,
  },
  {
    title: 'Changes to Terms',
    content: `We reserve the right to modify these terms at any time. We will notify you of material changes by posting a notice on our platform and sending you an email notification. Your continued use of SkillBridge AI after changes take effect constitutes acceptance of the updated terms.`,
  },
  {
    title: 'Contact Information',
    content: `For questions about these Terms of Service, please contact us:

**Email:** legal@skillbridge.ai  
**Address:** SkillBridge AI, 123 Innovation Drive, San Francisco, CA 94105  
**Legal Department:** legal@skillbridge.ai`,
  },
];

export default function TermsPage() {
  return (
    <div>
      {/* Hero */}
      <Section className="bg-gradient-to-b from-primary/5 to-transparent pt-24 md:pt-32">
        <Container>
          <div className="text-center max-w-3xl mx-auto">
            <nav className="flex items-center justify-center gap-2 text-sm text-muted-foreground mb-6">
              <Link href="/" className="hover:text-primary transition-colors">Home</Link>
              <ChevronRight className="w-4 h-4" />
              <span className="text-foreground">Terms of Service</span>
            </nav>
            <span className="font-overline text-primary mb-3 block">Legal</span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-heading tracking-tight mb-6">Terms of Service</h1>
            <p className="text-lg text-muted-foreground font-body">
              Please read these terms carefully before using SkillBridge AI. They govern your access to and use of our platform and services.
            </p>
            <p className="text-sm text-muted-foreground mt-4">
              Last updated: January 15, 2026
            </p>
          </div>
        </Container>
      </Section>

      {/* Content */}
      <Section>
        <Container>
          <div className="max-w-4xl mx-auto">
            <div className="prose prose-neutral dark:prose-invert max-w-none">
              <p className="text-muted-foreground leading-relaxed mb-8">
                These Terms of Service (Terms) govern your access to and use of the SkillBridge AI platform, website, and services (collectively, the Platform). By using the Platform, you agree to these Terms. Please read them carefully.
              </p>

              <div className="space-y-10">
                {sections.map((section, index) => (
                  <div key={index}>
                    <h2 className="text-2xl font-semibold tracking-tight mb-4">{section.title}</h2>
                    <div className="text-muted-foreground leading-relaxed whitespace-pre-line">
                      {section.content.split('\n\n').map((paragraph, pIndex) => {
                        if (paragraph.startsWith('**') && paragraph.includes(':**')) {
                          const parts = paragraph.split(':**');
                          return (
                            <p key={pIndex} className="mb-3">
                              <strong className="text-foreground">{parts[0]}:</strong>
                              {parts.slice(1).join(':**')}
                            </p>
                          );
                        }
                        if (paragraph.startsWith('- ')) {
                          const items = paragraph.split('\n').filter(line => line.startsWith('- '));
                          return (
                            <ul key={pIndex} className="list-disc pl-6 space-y-1 mb-3">
                              {items.map((item, iIndex) => (
                                <li key={iIndex}>{item.slice(2)}</li>
                              ))}
                            </ul>
                          );
                        }
                        return <p key={pIndex} className="mb-3">{paragraph}</p>;
                      })}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Container>
      </Section>
    </div>
  );
}
